ITEM.name = "Clipboard"
ITEM.description = "A thin, rigid board with a clip at the top for holding paper in place."
ITEM.model = "models/props_lab/clipboard.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.outfitCategory = "hands"
ITEM.pacData = {
    [1] = {
        ["children"] = {
            [1] = {
                ["children"] = {
                },
                ["self"] = {
                    ["Skin"] = 0,
                    ["Invert"] = false,
                    ["LightBlend"] = 1,
                    ["CellShade"] = -0.12,
                    ["OwnerName"] = "self",
                    ["AimPartName"] = "",
                    ["IgnoreZ"] = false,
                    ["AimPartUID"] = "",
                    ["Passes"] = 1,
                    ["Name"] = "",
                    ["NoTextureFiltering"] = false,
                    ["DoubleFace"] = false,
                    ["PositionOffset"] = Vector(6.6999998092651, -3, 0),
                    ["IsDisturbing"] = false,
                    ["Fullbright"] = false,
                    ["EyeAngles"] = false,
                    ["DrawOrder"] = 0,
                    ["TintColor"] = Vector(0, 0, 0),
                    ["UniqueID"] = "311453492",
                    ["Translucent"] = false,
                    ["LodOverride"] = -1,
                    ["BlurSpacing"] = 0,
                    ["Alpha"] = 0.8,
                    ["Material"] = "",
                    ["UseWeaponColor"] = false,
                    ["UsePlayerColor"] = false,
                    ["UseLegacyScale"] = false,
                    ["Bone"] = "right hand",
                    ["Color"] = Vector(255, 255, 255),
                    ["Brightness"] = 1,
                    ["BoneMerge"] = false,
                    ["BlurLength"] = 0,
                    ["Position"] = Vector(0.001708984375, -0.409423828125, -0.00054931640625),
                    ["AngleOffset"] = Angle(270, 0, 39.900001525879),
                    ["AlternativeScaling"] = false,
                    ["Hide"] = false,
                    ["OwnerEntity"] = false,
                    ["Scale"] = Vector(1, 1, 1),
                    ["ClassName"] = "model",
                    ["EditorExpand"] = false,
                    ["Size"] = 1,
                    ["ModelFallback"] = "",
                    ["Angles"] = Angle(0, 0, 0),
                    ["TextureFilter"] = 3,
                    ["Model"] = "models/props_lab/clipboard.mdl",
                    ["BlendMode"] = "",
                },
            },
            [2] = {
                ["children"] = {
                    [1] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["Jiggle"] = false,
                            ["DrawOrder"] = 0,
                            ["AlternativeBones"] = false,
                            ["FollowPartName"] = "",
                            ["Angles"] = Angle(0.00042005669092759, -78.330291748047, -0.0010778893483803),
                            ["OwnerName"] = "self",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "right forearm",
                            ["InvertHideMesh"] = false,
                            ["ScaleChildren"] = false,
                            ["ClassName"] = "bone2",
                            ["FollowAnglesOnly"] = false,
                            ["Position"] = Vector(0.000885009765625, -0.00189208984375, 0),
                            ["AimPartUID"] = "",
                            ["UniqueID"] = "2314686374",
                            ["Hide"] = false,
                            ["Name"] = "right forearm",
                            ["Scale"] = Vector(1, 1, 1),
                            ["MoveChildrenToOrigin"] = false,
                            ["EditorExpand"] = false,
                            ["Size"] = 1,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["EyeAngles"] = false,
                            ["HideMesh"] = false,
                        },
                    },
                    [2] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["Jiggle"] = false,
                            ["DrawOrder"] = 0,
                            ["AlternativeBones"] = false,
                            ["FollowPartName"] = "",
                            ["OwnerName"] = "self",
                            ["AimPartName"] = "",
                            ["FollowPartUID"] = "",
                            ["Bone"] = "right upperarm",
                            ["ScaleChildren"] = false,
                            ["FollowAnglesOnly"] = false,
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["Position"] = Vector(0, 0, 0),
                            ["AimPartUID"] = "",
                            ["UniqueID"] = "675386189",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["Scale"] = Vector(1, 1, 1),
                            ["MoveChildrenToOrigin"] = false,
                            ["Angles"] = Angle(13.065340995789, 2.4377853870392, 10.678699493408),
                            ["Size"] = 1,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["EditorExpand"] = false,
                            ["EyeAngles"] = false,
                            ["ClassName"] = "bone",
                        },
                    },
                },
                ["self"] = {
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "3308416632",
                    ["AimPartUID"] = "",
                    ["Hide"] = false,
                    ["Duplicate"] = false,
                    ["ClassName"] = "group",
                    ["OwnerName"] = "self",
                    ["IsDisturbing"] = false,
                    ["Name"] = "",
                    ["EditorExpand"] = true,
                },
            },
        },
        ["self"] = {
            ["DrawOrder"] = 0,
            ["UniqueID"] = "1625185648",
            ["AimPartUID"] = "",
            ["Hide"] = false,
            ["Duplicate"] = false,
            ["ClassName"] = "group",
            ["OwnerName"] = "self",
            ["IsDisturbing"] = false,
            ["Name"] = "my outfit",
            ["EditorExpand"] = true,
        }
    }
}