ITEM.name = "Facewrap"
ITEM.description = "A basic facewrap that covers the lower half of the face."
ITEM.model = "models/props_junk/cardboard_box004a.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.outfitCategory = "hat"
ITEM.price = 35
ITEM.pacData = {
	[1] = {
        ["children"] = {
            [1] = {
                ["children"] = {
                    [1] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "1465262828",
                            ["OwnerName"] = "self",
                            ["AimPartName"] = "",
                            ["Bone"] = "head",
                            ["Position"] = Vector(-0.2529296875, 0.7205810546875, 0.010894775390625),
                            ["AimPartUID"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["EditorExpand"] = false,
                            ["EyeAngles"] = false,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "clip",
                            ["Translucent"] = false,
                            ["Angles"] = Angle(0.033076476305723, -21.791984558105, -0.019590696319938),
                        },
                    },
                    [2] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "2257684031",
                            ["OwnerName"] = "self",
                            ["AimPartName"] = "",
                            ["Bone"] = "head",
                            ["Position"] = Vector(3.9892578125, 0.48583984375, -0.002410888671875),
                            ["AimPartUID"] = "",
                            ["Hide"] = false,
                            ["Name"] = "",
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["EditorExpand"] = false,
                            ["EyeAngles"] = false,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["ClassName"] = "clip",
                            ["Translucent"] = false,
                            ["Angles"] = Angle(-0.00034668546868488, -158.63916015625, 0.0012366912560537),
                        },
                    },
                },
                ["self"] = {
                    ["Skin"] = 0,
                    ["Invert"] = false,
                    ["LightBlend"] = 1,
                    ["CellShade"] = 0,
                    ["OwnerName"] = "self",
                    ["AimPartName"] = "",
                    ["IgnoreZ"] = false,
                    ["AimPartUID"] = "",
                    ["Passes"] = 1,
                    ["Name"] = "",
                    ["NoTextureFiltering"] = false,
                    ["DoubleFace"] = false,
                    ["PositionOffset"] = Vector(0, 0, 0),
                    ["IsDisturbing"] = false,
                    ["Fullbright"] = false,
                    ["EyeAngles"] = false,
                    ["DrawOrder"] = 0,
                    ["TintColor"] = Vector(255, 0, 0),
                    ["UniqueID"] = "3007355062",
                    ["Translucent"] = false,
                    ["LodOverride"] = -1,
                    ["BlurSpacing"] = 0,
                    ["Alpha"] = 1,
                    ["Material"] = "",
                    ["UseWeaponColor"] = false,
                    ["UsePlayerColor"] = false,
                    ["UseLegacyScale"] = false,
                    ["Bone"] = "head",
                    ["Color"] = Vector(255, 255, 255),
                    ["Brightness"] = 1,
                    ["BoneMerge"] = false,
                    ["BlurLength"] = 0,
                    ["Position"] = Vector(-6.396484375, -2.614501953125, -0.024978637695313),
                    ["AngleOffset"] = Angle(0, 0, 0),
                    ["AlternativeScaling"] = false,
                    ["Hide"] = false,
                    ["OwnerEntity"] = false,
                    ["Scale"] = Vector(1.0499999523163, 0.87000000476837, 1),
                    ["ClassName"] = "model",
                    ["EditorExpand"] = true,
                    ["Size"] = 1,
                    ["ModelFallback"] = "",
                    ["Angles"] = Angle(89.984359741211, 12.338585853577, 0),
                    ["TextureFilter"] = 3,
                    ["Model"] = "models/mask.mdl",
                    ["BlendMode"] = "",
                },
            },
        },
        ["self"] = {
            ["DrawOrder"] = 0,
            ["UniqueID"] = "2160586062",
            ["AimPartUID"] = "",
            ["Hide"] = false,
            ["Duplicate"] = false,
            ["ClassName"] = "group",
            ["OwnerName"] = "self",
            ["IsDisturbing"] = false,
            ["Name"] = "my outfit",
            ["EditorExpand"] = true,
        }
    }    
}